### ISSUE TITLE
sphinx error for generic functions

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#248]
After the refactoring of Reg I get the following error in the Morepath doc building:

/home/faassen/projects/morepath/doc/api.rst:17: WARNING: error while formatting arguments for morepath.settings: 'Dispatch' object has no attribute '__bases__'

even though the resulting documentation looks okay.

**Comment by taschini** [comment]
The error is generated when introspection is attempted on the generic functions in order to determine their signature.

The documentation looks *almost* all-right, but it signature for the generic functions is missing. See, .e.g., [``morepath.remember_identity``](http://morepath.readthedocs.io/en/0.14/api.html#morepath.remember_identity).

A stop-gap solution is simply to provide an explicit signature to Sphinx.

**Comment by faassen** [comment]
Thanks for the stop-gap. I am hoping we can do something cleverer eventually, so leaving this issue open for now.

**Comment by taschini** [comment]
Closed by morepath/reg#53.
