### ISSUE TITLE
Per-Request, Per-Application Settings

### ISSUE THREAD

**Issue by href** [morepath/morepath#294]
I have this idea, but I don't know if it is any good. Currently the settings have no way of accessing the app or the request. What if we added the ability to have settings that have access to the app or the request and gave them precedence over the basic settings:

That would mean that when calling `settings().chameleon.auto_reload` this:
```
@ChameleonApp.setting_section(section='chameleon')
def get_setting_section(request):
    return {'auto_reload': request.params.get('auto_reload')}
```
would have precendence over this:
```
@ChameleonApp.setting_section(section='chameleon')
def get_setting_section(app):
    return {'auto_reload': app.auto_reload}
```
which would have precedence over this:
```
@ChameleonApp.setting_section(section='chameleon')
def get_setting_section():
    return {'auto_reload': app.auto_reload}
```

I think it might make the settings more flexible and more usable for things like a more.email package, where the default mailhost would be defined as 'localhost:1025' with the ability to dynamically replace that setting on the application (which might load this information from a database).

From what I understand there are settings that are loaded at startup - so if the request or app is not available it would not be used to look up the setting. There would not be any guarantee. But I'm sure there are many cases where the settings are needed during a request, where it might make sense to have the ability to override them with information bound to the application or the request.

What do ya'll think?

**Comment by faassen** [comment]
I think per app and per request settings would be a useful thing. But as you say, the settings right now are loaded at startup very early. This also so that other directives can make use of the information there. (Settings are already per application already though -- you can override settings just like anything else.)

I can see why there might be a need for settings that are calculated dynamically though. Before we go this route we better make sure we have the use cases clear -- what would we use these settings for? And implementation-wise, how would we get auto-reload into a template engine during runtime?

I suspect if we want to go this route we either have to change the way settings work very fundamentally. But perhaps we can introduce another, non-settings concept that fills these use cases.

**Comment by href** [comment]
I was thinking that it might be nice to build 'more' packages. One could write a more.email package for example, which takes the host, username and so on from the static settings. This is a reasonable thing to do, as many unix systems accept mails sent to localhost:25 by default.

Someone using the package would then have the ability to override those settings per actual app instance or request. Which is useful if you want to store those settings in a database and load them at run time.

BUT: A package could provide this feature without Morepath's help, so I'm not sure we want to support this. Having an easy and powerful way to extend the settings would probably improve the chances that a 'more' package is useful for a wide audience, though it would still be coincidental, unless everyone codes under the assumption that settings change.

So yeah, I'm not sure I have a use case.

Can a setting be changed manually somehow? Because that would accomplish the same thing..

**Comment by faassen** [comment]
Closing this for now, we can always find it under 'ideas'.
