### ISSUE TITLE
Newbie trying to run the samples

### ISSUE THREAD

**Issue by seyhbold** [morepath/morepath#303]
Hi,

I tried to run the code from morepath_rest repository on Windows. It starts, but when I try to access a path I get the following:

```
Running <morepath_rest.main.App object at 0x000000000343A7B8> with wsgiref.simple_server on http://127.0.0.1:5000
Traceback (most recent call last):
  File "C:\Tools\python2\Lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Users\weissl\Envs\mp27\lib\site-packages\morepath\app.py", line 139, in __call__
    response = self.publish(request)
  File "C:\Users\weissl\Envs\mp27\lib\site-packages\morepath\publish.py", line 71, in publish
    return resolve_response(request, model)
  File "C:\Users\weissl\Envs\mp27\lib\site-packages\morepath\publish.py", line 46, in resolve_response
    view = generic.view.component(request, obj, lookup=request.lookup)
  File "C:\Users\weissl\Envs\mp27\lib\site-packages\reg\dispatch.py", line 58, in component
    return get_lookup(kw).component(self.wrapped_func, *args, **kw)
  File "C:\Users\weissl\Envs\mp27\lib\site-packages\reg\registry.py", line 424, in component
    key = self.key_lookup.predicate_key(callable, *args, **kw)
  File "C:\Users\weissl\Envs\mp27\lib\site-packages\reg\registry.py", line 223, in predicate_key
    raise KeyExtractorError()
KeyExtractorError
127.0.0.1 - - [26/Mar/2015 09:40:35] "GET / HTTP/1.1" 500 59
```

Could you please help me to figure out, what I am doing wrong?

* created a virtualenv
* `pip install morepath`
* copied the `morepath_rest` package into a folder 
* created a run.py:

```python
from morepath_rest.main import main

if __name__ == '__main__':
    main()
```

Thank you very much
I'd love to see morepath in action

Regards
Ludwig

**Comment by href** [comment]
I can reproduce your problem. The error you're seeing occurs because the Morepath application you are trying to run cannot be configured correctly. Morepath usually does that through an auto setup mechanism that scans *installed* packages for Morepath applications and their configuration (i.e. their paths, views and so on).

You said that you simply copied the morepath_rest example and added a run.py file to run the application in the parent folder of the example. This won't work because the main function of morepath_rest will use `morepath.autosetup` to scan for installed applications. Since morepath_rest is only copied, not installed, it will fail to find the configuration.

See https://github.com/morepath/morepath_rest/blob/master/morepath_rest/main.py
and http://morepath.readthedocs.org/en/latest/api.html#morepath.autoconfig

To fix this problem you can change your run.py to the following:

```python
import morepath
import morepath_rest

from morepath_rest.main import main

if __name__ == '__main__':
    config = morepath.autoconfig()
    config.scan(morepath_rest)
    config.commit()
    main()
```
In the above code, the autosetup is replaced by a somewhat manual configuration. Usually, morepath.autosetup would detect that morepath_rest is installed and it would run `config.scan` automatically. Since it is not installed, we can simply do it manually instead.

See http://morepath.readthedocs.org/en/latest/api.html#morepath.autoconfig

You can also just run `python setup.py develop` in the morepath_rest folder and your run.py should work, since the morepath_rest module would be installed this way and the autosetup mechanism should find it.

**Comment by seyhbold** [comment]
Thank you very much. This did it!

I guess I should learn how to deal with setup.py and all this stuff...

**Comment by href** [comment]
Don't sweat it. The configuration step can be a bit of a gotcha.

**Comment by seyhbold** [comment]
Hmm, you're right. I just figured, that I have to have `lxml` installed when adding `sqlalchemy` and `more.transaction` to the project and want to use `morepath.autoconfig()`. I found no way to install `lxml` to Python 3.4 64bit on Windows 64bit.
So I have to configure morepath manually.
