### ISSUE TITLE
introspection UI

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#315]
A web UI and/or commandline tools that introspect the application registries for paths and views and give information. Needs Morepath changes to add good introspection UIs to these registries, and then a separate project which contains the UI.

**Comment by faassen** [comment]
Okay, so it looks like I'm going to work on this in the near future. I need to go into Morepath and add APIs so that introspection is possible.

Then as a first stage build a command-line tool that you can use to ask questions such as: what paths are registered (and what models), or "tell me everything about this model" etc, which then give some human readable information that describes what's going on, ideally with line number information about where registrations happened.

**Comment by faassen** [comment]
I'd be very curious to hear your thoughts and wishes on this too, @href

**Comment by href** [comment]
Well I'm interested in learning about all the urls (paths + views) to generate documentation through it. I'll try to add a reflector to [sphinxcontrib.httpdomain](https://pythonhosted.org/sphinxcontrib-httpdomain/) once you've done some work on this.

The Flask shows quite nicely how useful this is for API documentation:
* [Application](https://github.com/jalaziz/sphinxcontrib-httpdomain/blob/master/test/autoflask_sampleapp.py)
* [Docs](https://pythonhosted.org/sphinxcontrib-httpdomain/#module-sphinxcontrib.autohttp.flask)

I think it might also be interesting to find out the permissions of each view for reviewing and testing permissions. I currently have a test that asserts that all my views *have* to specify a permission. If I could enumerate them I might also be able to add a test which simply compares all the permissions and views with a specific list. I can test for that in other ways, but this would be much easier to review.

I think it's generally interesting to get a nice representation of all the configuration out. I'm not sure what I would use it for to be frank, but if something is wrong we could inspect all the configuration state that the app carries in the debugger. Maybe we could even find out what was inherited, what comes from the app and what was overridden.

Ultimately it would really befit the elegance of Morepath if this worked with all directives. So if I write my own, I can find out about that as well. Not something I see any use for at the moment, just something that would be nice. I mean you *did* ask for my wishes ;)

Anyway, I realise I'm not telling you anything new and my use cases are kind of unimportant. You've also already picked up on sharing routing strings with javascript and generating routes without having to instantiate the model, which I was going to mention as well. But I'm really excited for this feature because it will make Morepath more user-friendly and easier to grok! This is going to lay a nice foundation for the future (and dare I say version 1.0 ;).

**Comment by faassen** [comment]
Thanks for the feedback, @href, it does help me a lot to hear these things. The connection to the configuration system is definitely an interesting one. A directive causes things to be registered with underlying registries, sometimes Reg-based, sometimes simpler stuff mixed into the application base class. Perhaps a directive can define one or more registration extraction operations as well, but I'm not sure what shape this operation should take yet.

**Comment by faassen** [comment]
There's now a command-line tool to query configuration actions in Dectate, but some issues were brought up here that are separate, so leaving this open for now until we can split this up into specific work items.

**Comment by faassen** [comment]
I've split up #373 with the meat of stuff so I can close this one.
