### ISSUE TITLE
Global policy app

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#354]
Sometimes it may be convenient to be able to define a policy for all apps in a process, no matter what they subclass. I imagine you could register a special global policy app that has its configuration overriding that in morepath.App but before any subclass overrides.

Is this worthwhile? It is an exception to the subclassing rule.

**Comment by href** [comment]
What's the use case for this? I mean if you want a global rule you can just inherit from a base application and not override the rule. Is it meant to prevent someone from overriding some rule?

**Comment by faassen** [comment]
The use case would be if you want to create an implicit policy for all
Morepath apps in the process. For instance a link_prefix policy. I am not
convinced it is needed as you could inherit from a common base app but this
way it would work even if you forget and it saves some typing as you don't
have to inherit from a base app everywhere.

**Comment by href** [comment]
If it can be done with inheritance I would not introduce a policy app. So that's a -1 from me. I think the best thing about Morepath is that nobody can force anything down your throat. You can take any Morepath application, inherit from it and then change it to your liking. You are always in charge because the base class you inherit from has no power over you. I'm preparing a talk which basically orbits around this central theme :)

**Comment by faassen** [comment]
Yes, that was my first response too, and so we're going to go on with inheritance. Closing this issue.
