### ISSUE TITLE
report if view is implemented for a model where no path directive exists

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#357]
How easy would it be to detect that a view is implemented for a model where no path directive at all exists for it or its base class? Is this an error or are there legitimate use cases for this? I think there are legitimate use cases, as you could implement a "framework app" that defines views for particular base classes.

We could however have a kind of report tool that reports on this as a possible problem.

**Comment by href** [comment]
> I think there are legitimate use cases, as you could implement a "framework app" that defines views for particular base classes.

There is another use case, though it only exists in theory from what I know: You can write a library which provides models and views together, but does not provide any paths. Someone using the library can then choose the paths themselves and indeed what models should actually be served under a path. For example, a blog library could define Post and Comment as well as some views, a library user could only serve Post however and not use comments at all.

But again, I don't plan to do it and I don't know if anyone else really ever has.

In any case I would love to see some kind of report tool because I'm interested in some introspection capabilities somewhere down the line (mainly to document all paths and views), which is a feature a good reporting tool might also require.

**Comment by faassen** [comment]
Yes, that use case, a library app that defines views and model classes is the one I was trying to talk about. But you work it out further; I just realized that any practical use of such a library would provide paths except where someone decides not to...

Yes, a reporting API and tool is something I expect I'll start work on soon.

**Comment by faassen** [comment]
Need to figure out whether and how the reporting tool can be used to report this.

**Comment by faassen** [comment]
I'm deferring particular use cases until after 0.14 when we got some more experience.

**Comment by faassen** [comment]
We're going to do this in a different way, by reporting what paths exist in the application.
