### ISSUE TITLE
Using the path action on classes in the dectate branch does not work as expected

### ISSUE THREAD

**Issue by href** [morepath/morepath#365]
I have this failing with a `dectate.error.ConflictError` in my tests using the dectate branch:

```python
@App.path('/')
class Model(object):
    pass

@App.path('/login')
class Login(object):
    pass
```

Looks like the model is None in this case.

**Comment by faassen** [comment]
Hm, interesting, I'll take a look.

**Comment by faassen** [comment]
Yes, I can replicate this! Astounding that the tests didn't catch this, but at least now there's a new test. :)

**Comment by href** [comment]
> Astounding that the tests didn't catch this

My thoughts exactly ;)

**Comment by faassen** [comment]
Ah, it's a consequence of me removing prepare for actions. In the past in prepare the model was set according to the class if the decorator is for a class. But the discriminators for the path make use of model, which is None in that case, which causes the conflict.

**Comment by faassen** [comment]
The special thing in the Path directive is that what is decorated in fact can cause a conflict error in this case. I think in fact when model is None, we should generate no discriminator, as it's not really possible to decorate the same class twice. Well, you *could* by employing two path decorators for the same class but I'll live with that edge case...

**Comment by faassen** [comment]
Hm, it could also conflict if you do a normal path decorator with an explicit model and also use a path decorator against a class. So I need to fix this in dectate itself...

**Comment by faassen** [comment]
Okay, turns out I could fix this by refactoring the action directive into two directives: the real action directive and a composite directive that generates the real action directives (and makes sure the model is the class). This was essentially what the old code was doing too, it was just all mixed together with the prepare() method.

Since the composite has access to the object being decorated I can generate the right information to go into the real path action. 

I did have to go and fix Dectate but only to improve the error reporting in case a DirectiveError is raised inside of a composite action.
