### ISSUE TITLE
auto-commit application upon instantiation

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#378]
We could automatically commit the app as it gets instantiated. Some subtleties:

It should commit classes only once as mounting can instantiate frequently. And if an app mounts others it should recursively commit them right away, otherwise mounted apps would be committed during runtime.

We do not want to commit during import time, so instantiating an app at top level is potentially problematic. But maybe that is okay -- doing a manual commit in ``__main__`` has the same issue.

Would it be possible to do this stuff in ``__new__`` so we don't put any requirement to do ``super`` on subclasses of ``App``?

@taschini

**Comment by faassen** [comment]
Hm, it turns out that even the check whether an app is committed before instantiated (released in 0.13.1) was problematic so I reversed it.

Real world code currently just instantiates apps on module level. Those apps are not usable until *after* their class gets committed, but that's perfectly feasible.

So doing configuration automatically when you instantiate an App is potentially problematic unless we change the rules about when you're allowed to instantiate an App.

**Comment by taschini** [comment]
Do I understand right, that the problem you described is caused by code like the following?

```
import morepath

class App(morepath.App):
    pass

app = App()

@App.path(path='')
class Root(object):
    pass

@App.view(model=Root)
def hello_world(self, request):
    return "Hello world!"

if __name__ == '__main__':
    morepath.autocommit()
    morepath.run(app)

```

**Comment by faassen** [comment]
Correct. We can either allow this pattern or somehow forbid it. If you left out the ``morepath.autocommit()`` call in this hypothetical scenario where instantiating the app triggers commit you'd get an application object that doesn't contain all the configuration needed.

**Comment by taschini** [comment]
Ok. So, let's call the above use case instantiate-configure-commit.  Then we have the use case of the quickstart app, configure-commit-instantiate, and the use case suggested in this issue: configure-instantiate (no explicit commit).

I personally don't like the instantiate-configure-commit use case, but if it's already out there I don't see enough reasons to disallow it.  If we implement the commit-on-instantiate idea, the use case will still work (the app will be committed twice, first-time on instantiation, and second time on explicit invocation of morepath.autocommit, but that's fine).  As you've already said, if you forget the explicit commit you'll get a misconfigured app, but this is already the case now, so no change in behaviour there.  In fact, one could try to be smarter  by using a lazy evaluation construct (perhaps your reify decorator) so that the commit takes place the first time the app is "used" instead of when it is initialized –– that would make the explicit commit completely redundant.

So what's your opinion: do you want to keep the status quo and support the instantiate-configure-commit use case? On the whole, I'd say yes.  If you agree, I'll add it as a test case, lest we forget this decision.

Now, regarding your other previous remarks.

> It should commit classes only once as mounting can instantiate frequently. 

Agreed.

> And if an app mounts others it should recursively commit them right away, otherwise mounted apps would be committed during runtime.

While I agree that recursive commit when the root app is committed is a sound idea, I'm not sure I understand why committing during runtime would be a problem: could you elaborate on that?

**Comment by faassen** [comment]
On changing configuration during runtime, whereby I mean after we've already started handling WSGI requests. Committing changes configuration registries. The configuration registries can make assumptions that they won't change during runtime -- in particular Reg can use caching strategies that would break. In addition, I think allowing a commit during runtime can lead to unpredictable behavior for the developer of the application.

It's true that an additional re-commit of an application previously committed but not fully configured should still work. But if people rely on "commit upon instantiate" behavior and they may not realize they can commit manually at all. We'd have to explain, no, you instantiated the app on top level and at this point imports weren't done yet and thus it only got half-committed and you get the weird behavior. (I realize we'd still get this if people did a commit on top-level, though. But a function call is less likely to be done on top-level than instantiation. I've added note in the install docs)

We could indeed move this behavior to the first time the application is *used*, but in that case instantiating really does *not* commit - instantiating would be as empty as it is now.

So I agree with you that introducing "instantiate is commit" would cause more trouble than it's worth. A test would be very welcome, good idea!

**Comment by faassen** [comment]
Another reason a commit during runtime is a bad idea is that it can show errors upon configuration conflicts and the like, and those could then appear during runtime triggered by end-user behavior. That would be bad.

**Comment by faassen** [comment]
Thank you for the test! While it's possible we'll revisit this sometime in the future, I'll close this issue now.

**Comment by taschini** [comment]
Actually, I think there is a way forward.  We need first something like an ``app.commit_configuration`` class method that does the kind of recursive discovery and commit that you described (and motivated) above.

That would allow a line like the [following](https://github.com/morepath/morepath/blob/0257e4d13cec8f2f0689a07db287c1808dd20aa5/morepath/tests/test_scenario.py#L16):

```
    dectate.commit(app.Root, app.Generic, app.Document)
```

to be replaced by 

```
    app.Root.commit_configuration()
```

Similarly for the tests in [test_mount_directive.py](https://github.com/morepath/morepath/blob/0257e4d13cec8f2f0689a07db287c1808dd20aa5/morepath/tests/test_mount_directive.py).

I think this first step is worthwhile even without the next step, which would have the app instance to invoke it unless `is_committed()` at some point before the first ``__call__()``.

**Comment by faassen** [comment]
good point. I spun this off into #383 for further discussion.
