### ISSUE TITLE
deprecation policy

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#389]
I've introduce an experimental deprecation policy for Morepath in the ``security.py`` -> ``authentication.py`` renaming. See security.py for a code example. This issue is to discuss how to move forward and how to make this an official policy (we should document these in the developing notes).

Basically something can become **deprecated** and we issue deprecation warnings for it, and people can turn on warnings to see them and update their code. Then in the next release, we mark it again in the changelog as **removed**, and remove the deprecation warnings. This gives people a chance to see the deprecation warnings before they upgrade.

I've documented this for users in ``upgrading.rst``.

This is not a strict story on doing deprecation warnings everywhere yet -- if it's too hard we'll just do a breaking change. To support more complex deprecation scenarios I'm considering introducing a dependency on ``zope.deprecation``.

**Comment by faassen** [comment]
@href, I'd appreciate your feedback.

**Comment by href** [comment]
I think this a good thing!

I like to keep things moving, but I think we should get used to those sooner or later. Currently we update the small ecosystem we have each time we introduce a breaking change into Morepath. Without deprecation we have to do this right when the new Morepath is released, otherwise our extensions do not work with the latest Morepath for a while after an update.

While this is sometimes necessary it should be minimised to decouple the release of Morepath from the release of all related packages. I think this shows a certain maturity and it paves the way for Morepath 1.0, though that's another discussion all together.

At the same time I think we should just aim for best effort. I wouldn't have wanted to deprecate our way through the dectate change for example.

**Comment by faassen** [comment]
I've written up this policy in developing.rst so we have it for future reference. This is now our hopefully lightweight policy. Closing this issue.

**Comment by faassen** [comment]
Oh, one extra note: I made part of the policy to create an issue labeled 'remove deprecated' in the tracker when we introduce a deprecation and assign it to the release after the upcoming one. That way we make sure we remove deprecation cruft in time. (I remember in Zope 3 the cruft optimistically declared when it was to be removed but then never was)
