### ISSUE TITLE
Phase out autosetup

### ISSUE THREAD

**Issue by taschini** [morepath/morepath#405]
With reference of #392, autosetup should be now phased out. I suggest we do it in two step:

1. Make autosetup equivalent to autoscan and raise a DeprecationWarning.

2. Finally remove autosetup.

**Comment by faassen** [comment]
There are some alternatives here. One is to go with autoscan everywhere, the other to go with autosetup everywhere and make it behave like autoscan. This is because autosetup is in use all over the place, and we could just keep it and let it work -- the commit behavior will however shift to the first run of the app as opposed to the end of the autosetup.

We also want to consider whether we want to make the "commit on use" behavior the one we recommend everywhere or whether for ease of explanation, ease of debugging and ease of performance measuring we make "commit" the default. Or perhaps we just explain somewhere you can always explicitly commit.

@href and @henri-hulski what do you think?

**Comment by href** [comment]
I was wondering if we might not go yet another way and just do `morepath.configure` or `morepath.setup` or something like this. Autosetup and and autoscan somehow seem like implementation details to me. All I need to know as a user is that Morepath needs some configuration or setup step before it can run my stuff. I don't need to be bothered with manual vs. auto and scan vs. setup.

**Comment by faassen** [comment]
Good point, @href. One argument against it is that ``morepath.setup`` would make it seem *necessary*, while it's only strictly useful pulling in dependencies (plus scanning the contents of the package itself). Plus we already had a ``morepath.setup`` until very recently.

I'd in fact be tempted to call it ``morepath.scan``, but we already have the true ``morepath.scan`` as a lower-level facility.

**Comment by href** [comment]
It would still be recommended though, right? If you add a scan step even if you don't need it you might avoid some problems when you grow your application (and forget all about morepath's scanning).

As we move on with Morepath to 1.0 and so forth it might be useful to always have this one call that sets up whatever configuration, scans, setup or housekeeping we need. Though we might be venturing into YAGNI territory.

**Comment by faassen** [comment]
To make progress: I think the simplest way forward is to call it ``autoscan``. This parallels ``scan``, which is the low-level version of this. We deprecate ``autosetup``. So go with @taschini's original plan.

I'm not sure what the "one call that sets up everything" would be -- really that's ``commit`` and now it happens automatically. I think letting the developer choose whether they want scan or not is a good idea, so we keep that separate, and yes, I think we should recommend using it. What it does now is only import stuff anyway.

**Comment by faassen** [comment]
We've cleared the way with Dectate release 0.10. What's needed:

* deprecate autosetup following the procedure described in `doc/developing.rst`

* remove autosetup and autocommit usage from the codebase and tests.

* remove autosetup and autocommit from the narrative docs.

* the API docs still have autocommit and autosetup for now, but has a **Deprecated** note in their docstring.

**Comment by taschini** [comment]
I can take care of the first two points tomorrow morning.

**Comment by faassen** [comment]
Okay, all adjusted now, thanks @taschini!
