### ISSUE TITLE
uploading huge files

### ISSUE THREAD

**Issue by faassen** [morepath/morepath#504]
Jan Stürtz reported a problem with the uploading of large files - when uploading a large file of 1.4 GB Morepath gave a memory error, and with 4.3 GB we got an Overflow error due to integer conversion issues.

He reports better behavior if we reverse the two checks in ``Request.body_obj``, which would imply that just checking whether ``self.body`` is empty in case of a large body actually does a lot of work. Since the large file is not a  JSON body reversing the checks would be okay, but it may be possible to replace things with an ``is None`` check instead too. We need to develop a testing strategy and investigate.

**Comment by href** [comment]
Nice, real world problems :)

Looking at WebOb's body property it becomes pretty clear why this check bites us:
https://github.com/Pylons/webob/blob/817096aa85d892d808da38ac48b99d70acf72277/webob/response.py#L520

So the whole body is indeed read with this truthiness test. We cannot touch the body if we want to avoid this. We need to use another property:

https://github.com/Pylons/webob/blob/817096aa85d892d808da38ac48b99d70acf72277/webob/response.py#L599

Note that this changed recently. With WebOb 1.6 there seems to be a `is_body_readable` instead of a `has_body` property. So we need to implement this with WebOb 1.7 in mind and release Morepath alongside it, or add our own compatibility shim.

**Comment by faassen** [comment]
Thanks for looking into this! Since webob 1.7 is already in RC we can assume it will be released soon. We could require 1.7 with the next release and then rely on its API, do you think that will bite anyone?

**Comment by href** [comment]
Hard to say, but if someone hypothetically relied on WebOb < 1.7 to do something they would probably pin their whole environment anyway (at least they should). The biggest problem is that WebOb is a bigger release, so it might introduce bugs that influence Morepath. But those would influence Morepath either way.

So I'd say go for it. We are pre-1.0 after all ;)

**Comment by faassen** [comment]
We'd have to require WebOb 1.7 or larger in your ``setup.py`` if we are going to depend on its API. Ah, I guess with pinning you mean they'd pin Morepath in some way too.

Yes, I think we are going to have to deal with WebOb 1.7 once it's released one way or another anyway. Luckily I ran into their performance regressions on master already and they already fixed them. :)

**Comment by href** [comment]
I also tested it against our stack, so I'm fairly confident it'll work. I'll also test it again before we release Morepath as always.

**Comment by href** [comment]
I fixed the issue (turns out `is_body_readable` was the right property after all). The following morepath application is now limited by the size of its buffer (instead of growing to the size of the uploaded file):

```python
import morepath

from pathlib import Path
from tempfile import TemporaryDirectory

class UploadApp(morepath.App):
    pass

@UploadApp.path(path='/')
class Upload(object):
    pass

@UploadApp.view(model=Upload, request_method='POST')
def handle_upload(self, request):
    """ Testcode, do not use! """

    buffer = 1024 * 1024
    upload = request.params['file'].file

    with TemporaryDirectory() as tmp:
        tempfile = Path(tmp) / 'file'

        with tempfile.open('wb') as f:
            for chunk in iter(lambda: upload.read(buffer), b''):
                f.write(chunk)

        return 'filesize: {} bytes'.format(tempfile.stat().st_size)

if __name__ == '__main__':
    morepath.run(UploadApp())
```

To test run:

`curl -F "file@/tmp/my-huge-wile" http://localhost:5000/`

This should return the size of the file. Note that there might be other issues when you're writing a an application that processes huge files. This depends on the implementation however. If there are other bugs we'd have to investigate with more concrete examples (say someone wanting to process a huge JSON file). Handling large files requires a lot of care is easy to get wrong.

**Comment by stuertz** [comment]
I could confirm this is fixed. The issue can be closed.
Seems to be fixed with https://github.com/morepath/morepath/commit/44224330efa5a757553f3b63f3cd789c375b26a0

**Comment by href** [comment]
Thanks for letting us know!
