### ISSUE TITLE
Demo stalls with combined browser GET, script POST actions

### ISSUE THREAD

**Issue by gmc444-b** [morepath/morepath#506]
I've been experimenting with the released versions of morepath and the morepath-rest-dump-load demo. Using the script below, the demo stalls under the following circumstance:

Use a standard browser (Chrome 54.0.2840.98) enter the request URL
"http://127.0.0.1:5000/customers".

In a terminal, use Python 3.5 to run the script below. the script will hang indefinitely. If I resubmit the URL above by hitting the refresh button in Chrome, the script unblocks and the POST succeeds.

If I restart the server and just run the script, the POST succeeds. I can also add GET requests in the script (not shown) and the script succeeds. Also, if I perform the GET request in another script, the POST request doesn't get stalled.

I'm concerned stalling will occur with scaling, or in a web server that combines REST and normal services. I'm running Python 3.5.2 on Mac El Capitan. I set everything up in a virtualenv, using pip to install morepath and the demo.

    # Requires Python 3.5                                                                                                                                                                                                
    from contextlib import closing
    from urllib.parse import urlencode
    from urllib.request import urlopen
    from urllib.request import Request
    import json
    
    url = 'http://127.0.0.1:5000/customers'
    data = {'@type': 'Customer', 'name': 'phil'}
    headers = {'content-type': 'application/json'}
    req = Request(url, data =json.dumps(data).encode(), headers=headers)
    with closing(urlopen(req)) as response:
        print(response.read().decode())

**Comment by href** [comment]
I tried to reproduce your error but I'm unable to. Here's what I did:

* I installed morepath and morepath-rest-dump-load using a virtualenv with Python 3.5
* I copied your testcode into a test.py file
* I started morepath_rest in one terminal
* I opened http://localhost:5000/customers in Chrome
* I ran `python test.py`

I couldn't witness any kind of hanging or stalling. I even ran your test script in parallel through bash (`python test.py & python test.py & python test.py`) and it works fine.

I further ran the apache test bench with a 1000 serial requests, while running your test-script and it was still responsive. What doesn't work is parallel requests with apache bench, but that's because we're not running morepath behind a webserver that queues/fans out the requests.

Can you provide more information about how to reproduce this problem? Am I missing something?

Generally you shouldn't see any stalling when using Morepath. If you did it would be a bug that we would fix. As far as I know nobody is running Morepath against thousands of requests per second yet, but we are doing benchmarks and we keep an eye on bottlenecks. Though my guess would be that in any kind of real-world application the request throughput will be dominated by factors other than Morepath.

**Comment by gmc444-b** [comment]
Thanks for investigating. After further research, it turns out that this might be a problem with Chrome. If i wait long enough, the script eventually unblocks, which looks like a timeout expiring. If I go into Chrome's dev tools and disable the cache, it no longer blocks. And if I use Safari instead of Chrome, the script doesn't block.
